apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark.fullname" . }}-master
  labels:
    {{- include "spark.labels" . | nindent 4 }}
    component: master
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.masterPort }}
      targetPort: master
      protocol: TCP
      name: master
    - port: {{ .Values.service.webuiPort }}
      targetPort: webui
      protocol: TCP
      name: webui
  selector:
    {{- include "spark.selectorLabels" . | nindent 4 }}
    component: master

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark.fullname" . }}-worker
  labels:
    {{- include "spark.labels" . | nindent 4 }}
    component: worker
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: worker
      protocol: TCP
      name: worker
  selector:
    {{- include "spark.selectorLabels" . | nindent 4 }}
    component: worker
